stages:
  - build
  - deploy

.build:
  stage: build
  before_script:
     - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME  --build-arg NODE_APP_INSTANCE=${NODE_APP_INSTANCE} .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  after_script:
    - docker logout $CI_REGISTRY
  tags:
    - pp-builder

build-branch:
  variables:
    NODE_APP_INSTANCE: develop
  extends: .build
  only:
    - develop

build-stage:
  variables:
    NODE_APP_INSTANCE: master
  extends: .build
  only:
    - master

build-prod:
  variables:
    NODE_APP_INSTANCE: prod
  extends: .build
  only:
    - /^\d+\.\d+\.\d+$/
  except:
    - branches

.deploy:
  stage: deploy
  variables:
    NODE_ENV: production
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker-compose pull
    - docker-compose -p 656-echo-explorer up -d
  after_script:
    - docker logout $CI_REGISTRY

develop:
  extends: .deploy
  variables:
    EXTERNAL_PORT: 26562
  environment:
    name: develop
    url: https://656-echo-explorer.pixelplex-test.by
  only:
    - develop
  tags:
    - pp-new-develop

stage-deploy:
  extends: .deploy
  variables:
    EXTERNAL_PORT: 36562
  environment:
    name: master
    url: http://656-echo-explorer.pixelplexlabs.com
  only:
    - master
  tags:
    - pp-stage

production-deploy:
  extends: .deploy
  variables:
    EXTERNAL_PORT: 26562
  environment:
    name: production
    url: https://explorer.echo-dev.io
  only:
    - /^\d+\.\d+\.\d+$/
  except:
    - branches
  tags:
    - echo-explorer-1